### PR TITLE
Encapsulate the implementations details of notebook model

### LINKED ISSUE #12: Overwrite getIndex, or do not use `container[]` ?
Is there a smart way to overwrite `myobj[index]` in typescript (I fail to find it on the internet). 
If so can we in some places wrap lists with `getIndex(index)` methods and use them ? (like [here](https://github.com/jupyter/phosphor-notebook/blob/master/src/NotebookComponent.ts#L195). Otherwise it make it hard to encapsulate Google real-time lists that do not provide a `myRealTimeList[index]`, but only `.get(index)` methods.

### PR DESCRIPTION
**Pull request by Carreau**
in particular do not directly assume cells is a list.

closes #12

---

Grrrr atom is auto-striping whitespace.

### CODE REVIEW

**Comment by sccolbert** [comment]
Is this ready for review?

**Comment by Carreau** [comment]
Hum, I believe so, unless you want me to revert stripping the whitespace.
I'm just using that as a base for working on real-time integration and haven't encounter any issues (though I was having lunch, so not extensively tested) 

One of the question I might have is wether we want `insert(index, value)`, or use the same signature as `splice(index, drop, values...)`, and wether we want `count` or keep a `length` property.

**Comment by sccolbert** [comment]
I think in general we should spend some time and sketch out the architecture of the notebook model. We can probably do better than what's currently there, and ensure that it has the required flexibility.

**Comment by Carreau** [comment]
Sure, I tend to work on prototype to see the issues I am hitting with google real-time. I don't trust myself  to be able to get all the corner by only thinking about it. 

One of the already weirds things I have, is that I need to pass 2 things around for now, the actual model, and a factory object to create the real-time instances. 

I would be much more careful about the design in each PRs if this was actually in production, but as it is (as far as I understand now ) a prototype, I don't see the harm in iterating quickly.

**Comment by sccolbert** [comment]
I think we should all probably get on a hangout and decide how we want to approach this big rewrite. I'd like to keep well-thought-out code bubbling into master. Maybe we can make some prototyping branches?

**Comment by Carreau** [comment]
Ok, so I can see that we might want 2 Notebook Interfaces. The serialization interface for JSON-like contents interface. And a In-Memory one. I'm fine with prototyping branches, but I'm not sure I see the differences from doing that in our own forked repos for now.

**Comment by sccolbert** [comment]
I don't think 2 notebook interfaces are necessary. JSON vs in-memory is an implementation detail which should be abstracted by an interface.

Forks are also fine, but I don't want to merge prototype code to master. We should at least have consensus on the architecture before merging and iterating.

**Comment by Carreau** [comment]
An interface for in Memory, if we want it to be baked by different real-time model, would be useful.
I doubt we want have Google Realtime baked into the core.

**Comment by sccolbert** [comment]
What I'm trying to say is that there should be 1 interface for a given set of functionality (`IWhateverContent`), with multiple implementations of that interface (`JupyterRealtime`, `GoogleRealtime`, etc...).

What we need to decide is how should these various bits of functionality be separated, what should their interfaces look like, and how they come together to form the `Notebook`.

**Comment by Carreau** [comment]
Ok, so communication problem then, we agree. 

Io'm going to close this as changing the current `Notebook` interface might not be the way to go. Though in some places things should note implement Notebook, but IWhateverContent.

**Pull request closed without merging**
